<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>inp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Mplus.inp</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i)\b(with|is|are|by|on|WITH|BY|ON|PWITH|at|AT|xwith|XWITH|ind|IND|via|VIA|ALL|if|then)\b</string>
			<key>name</key>
			<string>keyword.operator.mplus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>invalid.illegal.mplus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@|\*|\[|\]|\|</string>
			<key>name</key>
			<string>keyword.other.mplus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)*\b</string>
			<key>name</key>
			<string>constant.numeric.mplus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\bTITLE\b:|\bDATA\b:|\bVARIABLE\b:|\bMODEL\b:|\bANALYSIS\b:|\bOUTPUT\b:|\bDEFINE\b:|\bMODEL\b \bCONSTRAINT\b:|\bMODEL\b \bTEST\b:|\bMODEL\b \bPRIORS\b:|\bPLOT\b:|\bDATA IMPUTATION\b:|\bSAVEDATA\b:|\bMODEL\b\s(.+):)</string>
			<key>name</key>
			<string>entity.name.function.mplus</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>!</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.mplus</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%</string>
			<key>end</key>
			<string>%</string>
			<key>name</key>
			<string>markup.heading.mplus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(\w+\)|\(\w+\-\w+\)</string>
			<key>name</key>
			<string>support.variable.mplus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(USEVARIABLES|listwise|FILE|USEVAR|STD|STDYX|auxiliary|STDY|NAMES|grouping|group|MISSING|MODINDICES|STANDARDIZED|nobservations|residual|TECH1|TECH2|TECH3|TECH4|TECH5|TECH6|TECH7|TECH8|TECH9|estimator|bseed|biterations|ITERATIONS|TYPE|within|between|ITERATION|SAMPSTAT|bconvergence|cluster|ndatasets|new|impute|save|thin|classes|knownclass)\b</string>
			<key>name</key>
			<string>variable.language.mplus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(bayes|GENERAL|MEANSTRUCTURE|MISSING|STDEVIATIONS|means|MCOHORT|H1|RANDOM|COMPLEX|TWOLEVEL|BASIC|H1|RANDOM|MIXTURE|EFA|BASIC|LOGISTIC|ML|MLM|MLMV|MLR|MLF|MUML|WLS|WLSM|WLSMV|GLS|ULS|DELTA|THETA|LOGIT|LOGLINEAR|OFFLEMA|EM|ODLL|INTEGRATION|STANDARD|GAUSSHERMITE|MONTECARLO|STANDARD|OBSERVED|EXPECTED|COMBINATION|CONVERGENCE|COVARIANCE|CORRELATION)\b</string>
			<key>name</key>
			<string>entity.name.tag.mplus</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mplus</string>
	<key>uuid</key>
	<string>AD21200E-3501-4301-8492-32FC05376A3A</string>
</dict>
</plist>
